services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1-bookworm
    volumes:
      - ../../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

